server:
  port: 8080
  servlet:
    contextPath: /api
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/dsvonrf
    username: dsvonrfm
    password: epiO-Ji18J-Z2rw_bsNKF-TQnsyHAnt5
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

