name: 'Spring Gradle Build Action'
description: 'Reusable GitHub Action for performing a gradle build or running a gradle task.'
author: 'Spring'

inputs:
  java-version:
    description: 'Version of the JDK to use to run the Gradle command. Used in the actions/setup-java step.'
    required: false
    default: '17'
  distribution:
    description: 'Distribution of the JDK to use to run the Gradle command. Used in the actions/setup-java step.'
    required: false
    default: 'temurin'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
    - name: Set up gradle user name
      shell: bash
      run: |
        mkdir -p /home/runner/.gradle
        echo 'systemProp.user.name=spring-builds+github' >> /home/runner/.gradle/gradle.properties
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      env:
        GRADLE_USER_HOME: /home/runner/.gradle