name: Deploy Backend to Cloud Run
on:
  push:
    branches:
      - main

env:
  REGION: "asia-southeast1"
  SERVICE: "airbnbbackend"
  GOOGLE_CLOUD_PROJECT: "${{ secrets.GCP_PROJECT_ID }}"
  GOOGLE_CLOUD_KEYFILE: "${{ secrets.GCP_CREDENTIALS }}"
  SPRING_DATASOURCE_URL: "${{secrets.DATABASE_URL}}"
  SPRING_DATASOURCE_USERNAME: "${{DATABASE_USERNAME}}"
  SPRING_DATASOURCE_PASSWORD: "${{DATABASE_PASSWORD}}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: true
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
  APP_SERVICES_ACCOUNT_KEY: "${{APP_SERVICES_ACCOUNT_KEY}}"

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Build Image with Cloud Build
        uses: google-github-actions/cloudbuild@main
        with:
          name: 'gcr.io/$PROJECT_ID/$REPO_NAME'

      - name: Run on Cloud Run 
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: 'gcr.io/$PROJECT_ID/$REPO_NAME'
          region: 'asia-southeast1'
          platform: 'managed'
          revision_suffix: 'latest'
          allow_unauthenticated: true
          